language:
 - cpp

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
 - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "zhenya750-3"
    token:
      secure: $MY_SONAR

script:
 - qmake
 - make
 - ./tests/tests
  
after_success:
 - coveralls --root . -E ".*external.*" -E ".*tests.*"
 - build-wrapper-linux-x86-64 --out-dir bw-output make clean all 
 - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
email: false
